ALTER TABLE "users" ADD COLUMN "mfaEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN "totpSecret" TEXT;
ALTER TABLE "users" ADD COLUMN "mfaBackupCodes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
